version: "3.1"

services:
  mongodb:
    build: .docker/mongodb
    container_name: devsignin-mongodb
    image: mongo
    restart: always
    tty: true
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  devsigninapp:
    build: .
    entrypoint: .docker/entrypoint.sh
    container_name: devsignin-app
    ports:
      - "3000:3000"
    volumes:
      - .:/home/node/app
    depends_on:
      - mongodb
